class Locator(object):
    """Home test locators"""
    read_more_btn = ".product_tag-ruby a:nth-child(2)"
    review_tab_btn = "reviews_tab"
    five_stars_button = "star-5"
    review_field = "comment"
    name_field = "author"
    email_field = "email"
    submit_btn = "submit"

    """Login registration locators"""
    my_account_btn = "menu-item-50"
    email_field_registration = "reg_email"
    password_field_registration = "reg_password"
    registration_btn = "register"
    login_email_field = "username"
    login_password_field = "password"
    login_btn = "login"
    element_presence_check = ".woocommerce-MyAccount-navigation>ul li:nth-child(6)>a"

